(function () {
  "use strict";

  /*
   * Single source of truth for portfolio project content.
   * Used by the homepage, portfolio pages, and service page examples.
   */

  function project(options) {
    var platform = options.platform;
    var homeCategory = platform === "Shopify" || platform === "BigCommerce" || platform === "Volusion"
      ? "ecommerce"
      : "custom";
    var homeGroup = {
      Shopify: "shopify",
      BigCommerce: "bigcommerce",
      Volusion: "volusion",
      Webflow: "webflow",
      Wix: "wix",
      WordPress: "wordpress",
      WooCommerce: "wordpress",
    }[platform];
    var pageKey = {
      Shopify: "shopify",
      BigCommerce: "bigcommerce",
      Volusion: "volusion",
      Webflow: "webflow",
    }[platform] || "website-development";

    return {
      name: options.name,
      desc: options.features.join(", ") + " for a " + options.category.toLowerCase() + " project.",
      features: options.features,
      tags: options.tags,
      category: options.category,
      domain: options.domain,
      href: "portfolio-detail/portfolio-detail",
      home: { category: homeCategory, group: homeGroup },
      position: options.position,
      pages: options.pages || [{ key: pageKey }],
      services: options.services || [],
    };
  }

  var PROJECTS = {
    "usa-light": project({
      name: "USA LIGHT",
      category: "Lighting",
      domain: "usalight.com",
      platform: "Shopify",
      position: 1,
      tags: ["Shopify", "Liquid", "Migration", "App Integration"],
      features: ["Volusion to Shopify Migration", "Conversion Focused Redesign", "SEO & Performance", "Custom PIM Solution"],
      services: [{ key: "shopify" }],
    }),
    "geroo-jaipur": project({
      name: "GEROO JAIPUR",
      category: "Fashion",
      domain: "geroojaipur.com",
      platform: "Shopify",
      position: 2,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["CRO Redesign", "Technical SEO", "Performance Optimization", "App Integrations"],
      services: [{ key: "shopify" }, { key: "ui-ux-product-design", position: 1 }],
    }),
    "emmalou-s-kitchen": project({
      name: "EMMALOU'S KITCHEN",
      category: "Pet Nutrition",
      domain: "emmalouskitchen.com",
      platform: "Shopify",
      position: 3,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Custom Theme Development", "Brand Focused Experience", "Dynamic Product Experience", "Bundles & Subscriptions"],
      services: [{ key: "shopify" }],
    }),
    "bumbo-stationeries": project({
      name: "BUMBO STATIONERIES",
      category: "Stationeries",
      domain: "bumbokart.com",
      platform: "Shopify",
      position: 4,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Development"],
      features: ["Digital Experience Revamp", "Workflow Automation", "Custom App Development", "CRO Optimization"],
      services: [{ key: "shopify" }, { key: "ai-automation-solutions", position: 1 }],
    }),
    "lemke-berlin": project({
      name: "LEMKE BERLIN",
      category: "Craft Beer",
      domain: "lemke.berlin",
      platform: "Shopify",
      position: 5,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Theme Customization", "Technical SEO", "Performance Optimization", "Store Enhancements"],
      services: [{ key: "shopify" }],
    }),
    dharito: project({
      name: "DHARITO",
      category: "FMCG",
      domain: "dharito.com",
      platform: "Shopify",
      position: 6,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["New Brand Launch", "CRO Focused UX", "Membership Platform", "Technical SEO"],
      services: [{ key: "shopify" }],
    }),
    "quality-draft-solutions": project({
      name: "QUALITY DRAFT SOLUTIONS",
      category: "Commercial Equipment",
      domain: "qualitydraftsolutions.com",
      platform: "Shopify",
      position: 7,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["CRO Focused Redesign", "User Journey Optimization", "Technical SEO", "AI & Local Visibility"],
      services: [{ key: "shopify" }, { key: "ai-automation-solutions", position: 2 }],
    }),
    grin: project({
      name: "GRIN",
      category: "Oral Care",
      domain: "grinoralcare.com",
      platform: "Shopify",
      position: 8,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Custom Cart Experience", "Streamlined Checkout", "UX Enhancements", "Conversion Optimization"],
      services: [{ key: "shopify" }],
    }),
    "coosje-bright": project({
      name: "COOSJE BRIGHT",
      category: "Fashion Accessories",
      domain: "coosjebright.com",
      platform: "Shopify",
      position: 9,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["B2B Commerce Portal", "VAT & Tax Automation", "Customer Segmentation", "Custom Order Workflows"],
      services: [{ key: "shopify" }, { key: "erp-crm-development", position: 1 }],
    }),
    bushirt: project({
      name: "BUSHIRT",
      category: "Fashion",
      domain: "bushirt.in",
      platform: "Shopify",
      position: 10,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Complete Store Redesign", "Custom Cart Experience", "Performance Optimization", "Checkout Enhancements"],
      services: [{ key: "shopify" }],
    }),
    "don-vino": project({
      name: "DON VINO",
      category: "Fashion",
      domain: "donvino.in",
      platform: "Shopify",
      position: 11,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Store Optimization", "Performance Improvements", "Product Experience", "App Integrations"],
      services: [{ key: "shopify" }],
    }),
    "zen-edge": project({
      name: "ZEN EDGE",
      category: "Kitchenware",
      domain: "thezenedge.in",
      platform: "Shopify",
      position: 12,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Premium Store Redesign", "CRO Focused UX", "Product Discovery", "Social Media Creatives"],
      services: [{ key: "shopify" }, { key: "ui-ux-product-design", position: 2 }],
    }),
    "glorious-kreations": project({
      name: "GLORIOUS KREATIONS",
      category: "Home Decor",
      domain: "gloriouskreations.com",
      platform: "Shopify",
      position: 13,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Responsive Optimization", "Feature Enhancements", "UX Refinements", "Store Optimization"],
      services: [{ key: "shopify" }],
    }),
    "stone-and-tile": project({
      name: "STONE & TILE",
      category: "Home & Garden",
      domain: "stoneandtileshoppe.com",
      platform: "Shopify",
      position: 14,
      tags: ["Shopify", "Migration", "JavaScript", "App Integration", "Figma"],
      features: ["Liquid to Hydrogen Migration", "Custom Storefront", "Technical SEO", "App Integrations"],
      pages: [{ key: "shopify" }, { key: "headless", position: 1 }],
      services: [{ key: "shopify" }, { key: "headless", position: 1 }],
    }),
    medmaster: project({
      name: "MEDMASTER",
      category: "Medical Education",
      domain: "medmaster.net",
      platform: "Shopify",
      position: 15,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Website Redesign", "Navigation Optimization", "Landing Pages", "UX Improvements"],
      services: [{ key: "shopify" }, { key: "website-development", position: 1 }],
    }),
    "cottons-daily": project({
      name: "COTTONS DAILY",
      category: "Fashion",
      domain: "cottonsdaily.com",
      platform: "Shopify",
      position: 16,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Storefront Enhancements", "Product Discovery", "International Checkout Integration", "UX Optimization"],
      services: [{ key: "shopify" }],
    }),
    kaytar: project({
      name: "KAYTAR",
      category: "Home Decor",
      domain: "studiokaytar.com",
      platform: "Shopify",
      position: 17,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Responsive Optimization", "Mobile Experience Optimization", "UX Refinements", "Performance Optimization"],
      services: [{ key: "shopify" }],
    }),
    "nys-approved-vendor": project({
      name: "NYS APPROVED VENDOR",
      category: "Prison Packaging",
      domain: "nyapprovedvendor.com",
      platform: "Shopify",
      position: 18,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Store Redesign", "Custom Cart Experience", "Navigation Optimization", "Inmate Verification Integration"],
      services: [{ key: "shopify" }],
    }),
    buadep: project({
      name: "BUADEP",
      category: "Fashion",
      domain: "buadep.com",
      platform: "Shopify",
      position: 19,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Klaviyo Automation", "Strategic Upselling", "Mini Cart Optimization", "Product Page CRO"],
      services: [{ key: "shopify" }],
    }),
    "christi-harris": project({
      name: "CHRISTI HARRIS",
      category: "Skin Care",
      domain: "christiharris.com",
      platform: "Shopify",
      position: 20,
      tags: ["Shopify", "Migration", "JavaScript", "App Integration"],
      features: ["Volusion to Shopify Migration", "Complete Store Revamp", "CRO Optimization", "Technical SEO"],
      services: [{ key: "shopify" }],
    }),
    wellforces: project({
      name: "WELLFORCES",
      category: "Electronics",
      domain: "wellforces.co.nz",
      platform: "Shopify",
      position: 21,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Storefront Enhancements", "B2B Pricing", "Backorder System", "Technical SEO"],
      services: [{ key: "shopify" }, { key: "erp-crm-development", position: 2 }],
    }),
    "top-city-lighting": project({
      name: "TOP CITY LIGHTING",
      category: "Automotive Lighting",
      domain: "topcitylights.net",
      platform: "Shopify",
      position: 22,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Product Vehicle Mapping", "Custom Product Finder", "UX Enhancements", "Custom Development"],
      services: [{ key: "shopify" }],
    }),
    powersupplymall: project({
      name: "POWERSUPPLYMALL",
      category: "Electronics",
      domain: "powersupplymall.com",
      platform: "Shopify",
      position: 23,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Storefront Enhancements", "Backorder System", "Global Commerce", "Technical SEO"],
      services: [{ key: "shopify" }],
    }),
    farmveda: project({
      name: "FARMVEDA",
      category: "Food & Beverage",
      domain: "farmveda.in",
      platform: "Shopify",
      position: 24,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Premium Store Redesign", "Subscription Commerce", "Conversion Optimization", "Local Delivery Setup"],
      services: [{ key: "shopify" }],
    }),
    "shop-journey": project({
      name: "SHOP JOURNEY",
      category: "Medical Supplies",
      domain: "shopjourney.com",
      platform: "Shopify",
      position: 25,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Store Redesign", "UX Enhancements", "Product Discovery", "Shopping Experience"],
      services: [{ key: "shopify" }],
    }),
    "fortune-supply": project({
      name: "FORTUNE SUPPLY",
      category: "Supplies",
      domain: "fortunesupplys.com",
      platform: "Shopify",
      position: 26,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Store Redesign", "Login-Based Pricing", "Custom Cart Experience", "UX Optimization"],
      services: [{ key: "shopify" }, { key: "erp-crm-development", position: 3 }],
    }),
    "rebel-chola": project({
      name: "REBEL CHOLA",
      category: "Astrology & Spiritual Goods",
      domain: "rebelchola.com",
      platform: "Shopify",
      position: 27,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Birth Chart Integration", "Custom Product Experience", "Responsive Optimization", "UX Enhancements"],
      services: [{ key: "shopify" }],
    }),
    "de-hondenhok": project({
      name: "DE HONDENHOK",
      category: "Pet Accessories",
      domain: "hondenhokexpert.nl",
      platform: "Shopify",
      position: 28,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Custom Theme Development", "Brand Focused Experience", "Dynamic Product Experience", "Conversion Optimization"],
      services: [{ key: "shopify" }],
    }),
    "pure-and-sure": project({
      name: "PURE & SURE",
      category: "Home Care",
      domain: "purensure.co",
      platform: "Shopify",
      position: 29,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
      features: ["Product Page Experience", "Mini Cart Optimization", "Conversion Optimization", "UX Enhancements (PDP)"],
      services: [{ key: "shopify" }],
    }),
    "super-supplys": project({
      name: "SUPER SUPPLYS",
      category: "Supplies",
      domain: "supersupplys.com",
      platform: "Shopify",
      position: 30,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Store Redesign", "Customer-Specific Pricing", "Custom Cart Experience", "UX Optimization"],
      services: [{ key: "shopify" }],
    }),
    invuria: project({
      name: "INVURIA",
      category: "Baby Care",
      domain: "invuria.com",
      platform: "Shopify",
      position: 31,
      tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Klaviyo Integration", "Subscription Commerce", "Customer Retention", "Store Enhancements"],
      services: [{ key: "shopify" }],
    }),

    "wilson-inmate": project({
      name: "WILSON INMATE",
      category: "Prison Packaging",
      domain: "wilsoninmatepackageprogram.com",
      platform: "BigCommerce",
      position: 1,
      tags: ["BigCommerce", "JS", "Handlebar", "App Integration", "Migration"],
      features: ["Shopify to BigCommerce Migration", "Homepage Redesign", "Custom Cart Experience", "Subscription Management"],
      services: [{ key: "bigcommerce" }],
    }),
    "vaporize-us": project({
      name: "VAPORIZE US",
      category: "Vaping Products",
      domain: "vaporizeus.com",
      platform: "BigCommerce",
      position: 2,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Shipping & Tax Rules", "Product Catalog Updates", "Responsive Optimization", "Custom Store Logic"],
      services: [{ key: "bigcommerce" }],
    }),
    "impress-athletix": project({
      name: "IMPRESS ATHLETIX",
      category: "Sportswear",
      domain: "impressathletix.com",
      platform: "BigCommerce",
      position: 3,
      tags: ["BigCommerce", "JS", "Handlebar", "App Integration", "Migration"],
      features: ["Shift4Shop to BigCommerce Migration", "Custom Storefront", "Technical SEO", "Performance Optimization"],
      services: [{ key: "bigcommerce" }],
    }),
    "myth-industries": project({
      name: "MYTH INDUSTRIES",
      category: "Fire Arms",
      domain: "myth-industries.com",
      platform: "BigCommerce",
      position: 4,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Technical SEO", "Homepage Optimization", "Category Navigation", "Product Discovery"],
      services: [{ key: "bigcommerce" }],
    }),
    "the-biomed-guys": project({
      name: "THE BIOMED GUYS",
      category: "Medical Supplies",
      domain: "thebiomedguys.com",
      platform: "BigCommerce",
      position: 5,
      tags: ["BigCommerce", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
      features: ["Technical SEO", "Core Web Vitals", "Performance Optimization", "Search Visibility"],
      services: [{ key: "bigcommerce" }],
    }),
    "vitamins-kart": project({
      name: "VITAMINS KART",
      category: "Supplements / Nutrition",
      domain: "vitaminskart.com",
      platform: "BigCommerce",
      position: 6,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Premium Store Redesign", "Technical SEO", "Performance Optimization", "UX Enhancements"],
      services: [{ key: "bigcommerce" }],
    }),
    "blue-marlin-chronicles": project({
      name: "BLUE MARLIN CHRONICLES",
      category: "Fishing Gear",
      domain: "bluemarlinchronicles.com",
      platform: "BigCommerce",
      position: 7,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Mega Menu Design", "Custom Cart Experience", "Navigation Optimization", "UX Enhancements"],
      services: [{ key: "bigcommerce" }],
    }),
    "natural-bulk-supplies": project({
      name: "NATURAL BULK SUPPLIES",
      category: "Cosmetic Ingredients",
      domain: "naturalbulksupplies.com",
      platform: "BigCommerce",
      position: 8,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Homepage Optimization", "Product Experience", "Site Structure", "UX Enhancements"],
      services: [{ key: "bigcommerce" }],
    }),
    soccermadusa: project({
      name: "SOCCERMADUSA",
      category: "Soccer Merch",
      domain: "soccermadusa.com",
      platform: "BigCommerce",
      position: 9,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Store Modernization", "Navigation Optimization", "Technical SEO", "Accessibility Compliance"],
      services: [{ key: "bigcommerce" }],
    }),
    "indie-ella": project({
      name: "INDIE ELLA",
      category: "Fashion",
      domain: "indieella.com",
      platform: "BigCommerce",
      position: 10,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Premium Store Redesign", "Navigation Optimization", "Product Experience", "UX Enhancements"],
      services: [{ key: "bigcommerce" }, { key: "ui-ux-product-design", position: 3 }],
    }),
    cleanguards: project({
      name: "CLEANGUARDS",
      category: "Janitorial Supplies",
      domain: "cleanguards.com",
      platform: "BigCommerce",
      position: 11,
      tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
      features: ["Checkout Optimization", "Cart Experience", "UX Enhancements", "Store Optimization"],
      services: [{ key: "bigcommerce" }],
    }),

    alldogboots: project({
      name: "ALLDOGBOOTS",
      category: "Pet Accessories",
      domain: "alldogboots.com",
      platform: "Volusion",
      position: 1,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Dynamic Product Pages", "Mobile Optimization", "Smart Product Filters", "Product Experience"],
      services: [{ key: "volusion" }],
    }),
    "tpms-bargains": project({
      name: "TPMS BARGAINS",
      category: "Auto Parts",
      domain: "tpmsbargains.com",
      platform: "Volusion",
      position: 2,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Premium Store Redesign", "Conversion Optimization", "Technical SEO", "Schema Implementation"],
      services: [{ key: "volusion" }],
    }),
    "palette-by-nature": project({
      name: "PALETTE BY NATURE",
      category: "Hair Colour",
      domain: "palettebynature.com",
      platform: "Volusion",
      position: 3,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Performance Optimization", "Navigation Optimization", "Checkout Experience", "UX Enhancements"],
      services: [{ key: "volusion" }],
    }),
    "trade-show-displays-us": project({
      name: "TRADE SHOW DISPLAYS US",
      category: "Trade Show Displays",
      domain: "tradeshowdisplaysus.com",
      platform: "Volusion",
      position: 4,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Premium Store Redesign", "Conversion Optimization", "Technical SEO", "Core Web Vitals Optimization"],
      services: [{ key: "volusion" }],
    }),
    "exotic-fragrances": project({
      name: "EXOTIC FRAGRANCES",
      category: "Fragrance & Perfumes",
      domain: "exoticfragrances.com",
      platform: "Volusion",
      position: 5,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Navigation Optimization", "Store Architecture", "Product Discovery", "UX Enhancements"],
      services: [{ key: "volusion" }],
    }),
    "adorable-kids": project({
      name: "ADORABLE KIDS",
      category: "Kids Clothing",
      domain: "adorable-kids.com",
      platform: "Volusion",
      position: 6,
      tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
      features: ["Cart Optimization", "Mobile Optimization", "UX Enhancements", "Store Optimization"],
      services: [{ key: "volusion" }],
    }),

    "data-sketches": project({
      name: "DATA SKETCHES",
      category: "Data Visualization",
      domain: "datasketch.es",
      platform: "Webflow",
      position: 1,
      tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Blog Experience", "UI Enhancements", "Bug Resolution", "UX Optimization"],
      pages: [{ key: "webflow" }, { key: "website-development", position: 10 }],
      services: [{ key: "webflow" }, { key: "website-development", position: 10 }],
    }),
    mixvibes: project({
      name: "MIXVIBES",
      category: "Music Software",
      domain: "mixvibes.com",
      platform: "Webflow",
      position: 2,
      tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Premium Store Design", "Brand Experience", "Mobile Optimization", "Technical SEO"],
      pages: [{ key: "webflow" }, { key: "website-development", position: 11 }],
      services: [{ key: "webflow" }, { key: "website-development", position: 11 }],
    }),
    "instant-systems": project({
      name: "INSTANT SYSTEMS",
      category: "Smart Kiosks / Automation",
      domain: "instantsystems.se",
      platform: "Webflow",
      position: 3,
      tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Premium Store Design", "Product Experience", "Mobile Optimization", "Performance Optimization"],
      pages: [{ key: "webflow" }, { key: "website-development", position: 12 }],
      services: [{ key: "webflow" }, { key: "website-development", position: 12 }],
    }),
    quantel: project({
      name: "QUANTEL",
      category: "Wealth Tech / Fintech",
      domain: "quantel.ai",
      platform: "Webflow",
      position: 4,
      tags: ["Webflow", "HTML / CSS", "JavaScript", "Figma"],
      features: ["Figma Implementation", "Custom Page Development", "Mobile Optimization", "UX Enhancements"],
      pages: [{ key: "webflow" }, { key: "website-development", position: 13 }],
      services: [{ key: "webflow" }, { key: "website-development", position: 13 }],
    }),

    "dr-mindy-pelz": project({
      name: "DR. MINDY PELZ",
      category: "Women's Wellness",
      domain: "drmindypelz.com",
      platform: "Wix",
      position: 1,
      tags: ["Wix", "HTML / CSS", "JavaScript", "App Integration"],
      features: ["Website Design", "Brand Experience", "Custom Landing Pages", "Mobile Optimization"],
      services: [{ key: "website-development", position: 2 }],
    }),
    "dumb-ways-to-die": project({
      name: "DUMB WAYS TO DIE",
      category: "Gaming",
      domain: "dumbwaystodie.com",
      platform: "Wix",
      position: 2,
      tags: ["Wix", "HTML / CSS", "JavaScript", "Figma"],
      features: ["Interactive Experience", "Custom Frontend", "Motion Design", "Performance Optimization"],
      services: [{ key: "website-development", position: 3 }],
    }),

    "darshan-metal": project({
      name: "DARSHAN METAL",
      category: "Metal Supply",
      domain: "darshanmetal.in",
      platform: "WordPress",
      position: 1,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Website Design", "Product Showcase", "Quote Request System", "User Experience"],
      services: [{ key: "website-development", position: 4 }],
    }),
    "akshar-technocast": project({
      name: "AKSHAR TECHNOCAST",
      category: "Industrial Manufacturing",
      domain: "akshargroups.in",
      platform: "WordPress",
      position: 2,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Corporate Website Design", "Performance Optimization", "Information Architecture", "Trust-Building UX"],
      services: [{ key: "website-development", position: 5 }],
    }),
    globaltv: project({
      name: "GLOBALTV",
      category: "Digital Media",
      domain: "globaltv.in",
      platform: "WordPress",
      position: 3,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["News Portal Design", "Content Architecture", "Navigation Optimization", "Performance Optimization"],
      services: [{ key: "website-development", position: 6 }],
    }),
    "that-computer-chap": project({
      name: "THAT COMPUTER CHAP",
      category: "IT Services",
      domain: "thatcomputerchap.co.uk",
      platform: "WordPress",
      position: 4,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Product Experience", "Navigation Optimization", "Store Architecture", "Shopping Experience"],
      services: [{ key: "website-development", position: 7 }],
    }),
    "online-ambassadors": project({
      name: "ONLINE AMBASSADORS",
      category: "Software & Digital Agency",
      domain: "onlineambassadors.net",
      platform: "WordPress",
      position: 5,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Premium Website Design", "Brand Experience", "Conversion Optimization", "Visual Hierarchy"],
      services: [{ key: "website-development", position: 8 }],
    }),
    "mega-media-news": project({
      name: "MEGA MEDIA NEWS",
      category: "News Portal",
      domain: "megamedianews.com",
      platform: "WordPress",
      position: 6,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["News Portal Design", "Content Architecture", "Navigation Optimization", "Reading Experience"],
      services: [{ key: "website-development", position: 9 }],
    }),
    fxhyp: project({
      name: "FXHYP",
      category: "Forex Education",
      domain: "fxhyp.com",
      platform: "WordPress",
      position: 7,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Premium Website Design", "Trust-Centered UX", "Information Architecture", "Brand Experience"],
      services: [{ key: "website-development", position: 14 }],
    }),
    "gaav-naturals": project({
      name: "GAAV NATURALS",
      category: "Natural Honey",
      domain: "gaavnaturals.in",
      platform: "WooCommerce",
      position: 8,
      tags: ["WordPress", "WooCommerce", "JS", "HTML / CSS", "App Integration"],
      features: ["Store Setup", "Navigation Optimization", "Checkout Experience", "Product Discovery"],
      services: [{ key: "website-development", position: 15 }],
    }),
    "onsite-tech-solutions": project({
      name: "ONSITE TECH SOLUTIONS",
      category: "Managed IT Services",
      domain: "onsitetechsolutions.com.au",
      platform: "WordPress",
      position: 9,
      tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
      features: ["Modern Storefront", "Responsive Design", "User Experience", "Interface Optimization"],
      services: [{ key: "website-development", position: 16 }],
    }),
  };

  var GROUPS = {
    ecommerce: [
      { id: "shopify", label: "Shopify" },
      { id: "bigcommerce", label: "BigCommerce" },
      { id: "volusion", label: "Volusion" },
    ],
    custom: [{ id: "webflow", label: "Webflow" }],
  };

  window.PORTFOLIO_DATA = {
    projects: PROJECTS,
    groups: GROUPS,
  };
})();
