/*
 * Portfolio projects — migrated verbatim from the legacy js/portfolio-data.js.
 *
 * TEMPORARY SOURCE: stage 3 imports this data into Sanity, after which the
 * site reads projects from Sanity and this file is only used by the import script.
 *
 * pages / services: which portfolio pages and service-page example lists the
 * project appears in, with an optional position override (defaults to `position`).
 */
import type { ProjectRecord } from "@/lib/projects/types";

export const projectRecords: ProjectRecord[] = [
  {
    slug: "usa-light",
    name: "USA LIGHT",
    category: "Lighting",
    domain: "usalight.com",
    platform: "Shopify",
    position: 1,
    tags: ["Shopify", "Liquid", "Migration", "App Integration"],
    features: [
      "Volusion to Shopify Migration",
      "Conversion Focused Redesign",
      "SEO & Performance",
      "Custom PIM Solution",
    ],
    image: "/project-images/full website/usalight.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "geroo-jaipur",
    name: "GEROO JAIPUR",
    category: "Fashion",
    domain: "geroojaipur.com",
    platform: "Shopify",
    position: 2,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["CRO Redesign", "Technical SEO", "Performance Optimization", "App Integrations"],
    image: "/project-images/full website/geroojaipur.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "ui-ux-product-design", position: 1 }],
  },
  {
    slug: "emmalou-s-kitchen",
    name: "EMMALOU'S KITCHEN",
    category: "Pet Nutrition",
    domain: "emmalouskitchen.com",
    platform: "Shopify",
    position: 3,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: [
      "Custom Theme Development",
      "Brand Focused Experience",
      "Dynamic Product Experience",
      "Bundles & Subscriptions",
    ],
    image: "/project-images/full website/emmalouskitchen.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "bumbo-stationeries",
    name: "BUMBO STATIONERIES",
    category: "Stationeries",
    domain: "bumbokart.com",
    platform: "Shopify",
    position: 4,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Development"],
    features: [
      "Digital Experience Revamp",
      "Workflow Automation",
      "Custom App Development",
      "CRO Optimization",
    ],
    image: "/project-images/full website/bumbokart.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "ai-automation-solutions", position: 1 }],
  },
  {
    slug: "lemke-berlin",
    name: "LEMKE BERLIN",
    category: "Craft Beer",
    domain: "lemke.berlin",
    platform: "Shopify",
    position: 5,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: ["Theme Customization", "Technical SEO", "Performance Optimization", "Store Enhancements"],
    image: "/project-images/full website/lemke.berlin.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "dharito",
    name: "DHARITO",
    category: "FMCG",
    domain: "dharito.com",
    platform: "Shopify",
    position: 6,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["New Brand Launch", "CRO Focused UX", "Membership Platform", "Technical SEO"],
    image: "/project-images/full website/dharito.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "quality-draft-solutions",
    name: "QUALITY DRAFT SOLUTIONS",
    category: "Commercial Equipment",
    domain: "qualitydraftsolutions.com",
    platform: "Shopify",
    position: 7,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["CRO Focused Redesign", "User Journey Optimization", "Technical SEO", "AI & Local Visibility"],
    image: "/project-images/full website/qualitydraftsolutions.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "ai-automation-solutions", position: 2 }],
  },
  {
    slug: "grin",
    name: "GRIN",
    category: "Oral Care",
    domain: "grinoralcare.com",
    platform: "Shopify",
    position: 8,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Custom Cart Experience",
      "Streamlined Checkout",
      "UX Enhancements",
      "Conversion Optimization",
    ],
    image: "/project-images/full website/grinoralcare.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "coosje-bright",
    name: "COOSJE BRIGHT",
    category: "Fashion Accessories",
    domain: "coosjebright.com",
    platform: "Shopify",
    position: 9,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: [
      "B2B Commerce Portal",
      "VAT & Tax Automation",
      "Customer Segmentation",
      "Custom Order Workflows",
    ],
    image: "/project-images/full website/coosjebright.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "erp-crm-development", position: 1 }],
  },
  {
    slug: "bushirt",
    name: "BUSHIRT",
    category: "Fashion",
    domain: "bushirt.in",
    platform: "Shopify",
    position: 10,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: [
      "Complete Store Redesign",
      "Custom Cart Experience",
      "Performance Optimization",
      "Checkout Enhancements",
    ],
    image: "/project-images/full website/bushirt.in.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "don-vino",
    name: "DON VINO",
    category: "Fashion",
    domain: "donvino.in",
    platform: "Shopify",
    position: 11,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: ["Store Optimization", "Performance Improvements", "Product Experience", "App Integrations"],
    image: "/project-images/full website/donvino.in.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "zen-edge",
    name: "ZEN EDGE",
    category: "Kitchenware",
    domain: "thezenedge.in",
    platform: "Shopify",
    position: 12,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: ["Premium Store Redesign", "CRO Focused UX", "Product Discovery", "Social Media Creatives"],
    image: "/project-images/full website/thezenedge.in.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "ui-ux-product-design", position: 2 }],
  },
  {
    slug: "glorious-kreations",
    name: "GLORIOUS KREATIONS",
    category: "Home Decor",
    domain: "gloriouskreations.com",
    platform: "Shopify",
    position: 13,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: ["Responsive Optimization", "Feature Enhancements", "UX Refinements", "Store Optimization"],
    image: "/project-images/full website/gloriouskreations.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "stone-and-tile",
    name: "STONE & TILE",
    category: "Home & Garden",
    domain: "stoneandtileshoppe.com",
    platform: "Shopify",
    position: 14,
    tags: ["Shopify", "Migration", "JavaScript", "App Integration", "Figma"],
    features: ["Liquid to Hydrogen Migration", "Custom Storefront", "Technical SEO", "App Integrations"],
    image: "/project-images/full website/stoneandtileshoppe.com.webp",
    pages: [{ key: "shopify" }, { key: "headless", position: 1 }],
    services: [{ key: "shopify" }, { key: "headless", position: 1 }],
  },
  {
    slug: "medmaster",
    name: "MEDMASTER",
    category: "Medical Education",
    domain: "medmaster.net",
    platform: "Shopify",
    position: 15,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: ["Website Redesign", "Navigation Optimization", "Landing Pages", "UX Improvements"],
    image: "/project-images/full website/medmaster.net.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "website-development", position: 1 }],
  },
  {
    slug: "cottons-daily",
    name: "COTTONS DAILY",
    category: "Fashion",
    domain: "cottonsdaily.com",
    platform: "Shopify",
    position: 16,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: [
      "Storefront Enhancements",
      "Product Discovery",
      "International Checkout Integration",
      "UX Optimization",
    ],
    image: "/project-images/full website/cottonsdaily.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "kaytar",
    name: "KAYTAR",
    category: "Home Decor",
    domain: "studiokaytar.com",
    platform: "Shopify",
    position: 17,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Responsive Optimization",
      "Mobile Experience Optimization",
      "UX Refinements",
      "Performance Optimization",
    ],
    image: "/project-images/full website/studiokaytar.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "nys-approved-vendor",
    name: "NYS APPROVED VENDOR",
    category: "Prison Packaging",
    domain: "nyapprovedvendor.com",
    platform: "Shopify",
    position: 18,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: [
      "Store Redesign",
      "Custom Cart Experience",
      "Navigation Optimization",
      "Inmate Verification Integration",
    ],
    image: "/project-images/full website/nyapprovedvendor.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "buadep",
    name: "BUADEP",
    category: "Fashion",
    domain: "buadep.com",
    platform: "Shopify",
    position: 19,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Klaviyo Automation", "Strategic Upselling", "Mini Cart Optimization", "Product Page CRO"],
    image: "/project-images/full website/buadep.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "christi-harris",
    name: "CHRISTI HARRIS",
    category: "Skin Care",
    domain: "christiharris.com",
    platform: "Shopify",
    position: 20,
    tags: ["Shopify", "Migration", "JavaScript", "App Integration"],
    features: ["Volusion to Shopify Migration", "Complete Store Revamp", "CRO Optimization", "Technical SEO"],
    image: "/project-images/full website/christiharris.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "wellforces",
    name: "WELLFORCES",
    category: "Electronics",
    domain: "wellforces.co.nz",
    platform: "Shopify",
    position: 21,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: ["Storefront Enhancements", "B2B Pricing", "Backorder System", "Technical SEO"],
    image: "/project-images/full website/wellforces.co.nz.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "erp-crm-development", position: 2 }],
  },
  {
    slug: "top-city-lighting",
    name: "TOP CITY LIGHTING",
    category: "Automotive Lighting",
    domain: "topcitylights.net",
    platform: "Shopify",
    position: 22,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: ["Product Vehicle Mapping", "Custom Product Finder", "UX Enhancements", "Custom Development"],
    image: "/project-images/full website/topcitylights.net.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "powersupplymall",
    name: "POWERSUPPLYMALL",
    category: "Electronics",
    domain: "powersupplymall.com",
    platform: "Shopify",
    position: 23,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Storefront Enhancements", "Backorder System", "Global Commerce", "Technical SEO"],
    image: "/project-images/full website/powersupplymall.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "farmveda",
    name: "FARMVEDA",
    category: "Food & Beverage",
    domain: "farmveda.in",
    platform: "Shopify",
    position: 24,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Premium Store Redesign",
      "Subscription Commerce",
      "Conversion Optimization",
      "Local Delivery Setup",
    ],
    image: "/project-images/full website/farmveda.in.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "shop-journey",
    name: "SHOP JOURNEY",
    category: "Medical Supplies",
    domain: "shopjourney.com",
    platform: "Shopify",
    position: 25,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: ["Store Redesign", "UX Enhancements", "Product Discovery", "Shopping Experience"],
    image: "/project-images/full website/shopjourney.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "fortune-supply",
    name: "FORTUNE SUPPLY",
    category: "Supplies",
    domain: "fortunesupplys.com",
    platform: "Shopify",
    position: 26,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Store Redesign", "Login-Based Pricing", "Custom Cart Experience", "UX Optimization"],
    image: "/project-images/full website/fortunesupplys.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }, { key: "erp-crm-development", position: 3 }],
  },
  {
    slug: "rebel-chola",
    name: "REBEL CHOLA",
    category: "Astrology & Spiritual Goods",
    domain: "rebelchola.com",
    platform: "Shopify",
    position: 27,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Birth Chart Integration",
      "Custom Product Experience",
      "Responsive Optimization",
      "UX Enhancements",
    ],
    image: "/project-images/full website/rebelchola.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "de-hondenhok",
    name: "DE HONDENHOK",
    category: "Pet Accessories",
    domain: "hondenhokexpert.nl",
    platform: "Shopify",
    position: 28,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Custom Theme Development",
      "Brand Focused Experience",
      "Dynamic Product Experience",
      "Conversion Optimization",
    ],
    image: "/project-images/full website/hondenhokexpert.nl.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "pure-and-sure",
    name: "PURE & SURE",
    category: "Home Care",
    domain: "purensure.co",
    platform: "Shopify",
    position: 29,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript"],
    features: [
      "Product Page Experience",
      "Mini Cart Optimization",
      "Conversion Optimization",
      "UX Enhancements (PDP)",
    ],
    image: "/project-images/full website/purensure.co.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "super-supplys",
    name: "SUPER SUPPLYS",
    category: "Supplies",
    domain: "supersupplys.com",
    platform: "Shopify",
    position: 30,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Store Redesign", "Customer-Specific Pricing", "Custom Cart Experience", "UX Optimization"],
    image: "/project-images/full website/supersupplys.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "invuria",
    name: "INVURIA",
    category: "Baby Care",
    domain: "invuria.com",
    platform: "Shopify",
    position: 31,
    tags: ["Shopify", "Liquid", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Klaviyo Integration", "Subscription Commerce", "Customer Retention", "Store Enhancements"],
    image: "/project-images/full website/invuria.com.webp",
    pages: [{ key: "shopify" }],
    services: [{ key: "shopify" }],
  },
  {
    slug: "wilson-inmate",
    name: "WILSON INMATE",
    category: "Prison Packaging",
    domain: "wilsoninmatepackageprogram.com",
    platform: "BigCommerce",
    position: 1,
    tags: ["BigCommerce", "JS", "Handlebar", "App Integration", "Migration"],
    features: [
      "Shopify to BigCommerce Migration",
      "Homepage Redesign",
      "Custom Cart Experience",
      "Subscription Management",
    ],
    image: "/project-images/full website/wilsoninmatepackageprogram.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "vaporize-us",
    name: "VAPORIZE US",
    category: "Vaping Products",
    domain: "vaporizeus.com",
    platform: "BigCommerce",
    position: 2,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: [
      "Shipping & Tax Rules",
      "Product Catalog Updates",
      "Responsive Optimization",
      "Custom Store Logic",
    ],
    image: "/project-images/full website/vaporizeus.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "impress-athletix",
    name: "IMPRESS ATHLETIX",
    category: "Sportswear",
    domain: "impressathletix.com",
    platform: "BigCommerce",
    position: 3,
    tags: ["BigCommerce", "JS", "Handlebar", "App Integration", "Migration"],
    features: [
      "Shift4Shop to BigCommerce Migration",
      "Custom Storefront",
      "Technical SEO",
      "Performance Optimization",
    ],
    image: "/project-images/full website/impressathletix.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "myth-industries",
    name: "MYTH INDUSTRIES",
    category: "Fire Arms",
    domain: "myth-industries.com",
    platform: "BigCommerce",
    position: 4,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Technical SEO", "Homepage Optimization", "Category Navigation", "Product Discovery"],
    image: "/project-images/full website/myth-industries.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "the-biomed-guys",
    name: "THE BIOMED GUYS",
    category: "Medical Supplies",
    domain: "thebiomedguys.com",
    platform: "BigCommerce",
    position: 5,
    tags: ["BigCommerce", "HTML / CSS", "JavaScript", "App Integration", "Figma"],
    features: ["Technical SEO", "Core Web Vitals", "Performance Optimization", "Search Visibility"],
    image: "/project-images/full website/thebiomedguys.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "vitamins-kart",
    name: "VITAMINS KART",
    category: "Supplements / Nutrition",
    domain: "vitaminskart.com",
    platform: "BigCommerce",
    position: 6,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Premium Store Redesign", "Technical SEO", "Performance Optimization", "UX Enhancements"],
    image: "/project-images/full website/vitaminskart.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "blue-marlin-chronicles",
    name: "BLUE MARLIN CHRONICLES",
    category: "Fishing Gear",
    domain: "bluemarlinchronicles.com",
    platform: "BigCommerce",
    position: 7,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Mega Menu Design", "Custom Cart Experience", "Navigation Optimization", "UX Enhancements"],
    image: "/project-images/full website/bluemarlinchronicles.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "natural-bulk-supplies",
    name: "NATURAL BULK SUPPLIES",
    category: "Cosmetic Ingredients",
    domain: "naturalbulksupplies.com",
    platform: "BigCommerce",
    position: 8,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Homepage Optimization", "Product Experience", "Site Structure", "UX Enhancements"],
    image: "/project-images/full website/naturalbulksupplies.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "soccermadusa",
    name: "SOCCERMADUSA",
    category: "Soccer Merch",
    domain: "soccermadusa.com",
    platform: "BigCommerce",
    position: 9,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Store Modernization", "Navigation Optimization", "Technical SEO", "Accessibility Compliance"],
    image: "/project-images/full website/soccermadusa.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "indie-ella",
    name: "INDIE ELLA",
    category: "Fashion",
    domain: "indieella.com",
    platform: "BigCommerce",
    position: 10,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Premium Store Redesign", "Navigation Optimization", "Product Experience", "UX Enhancements"],
    image: "/project-images/full website/indieella.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }, { key: "ui-ux-product-design", position: 3 }],
  },
  {
    slug: "cleanguards",
    name: "CLEANGUARDS",
    category: "Janitorial Supplies",
    domain: "cleanguards.com",
    platform: "BigCommerce",
    position: 11,
    tags: ["BigCommerce", "Stencil", "Handlebar", "HTML / CSS", "JS", "App Integration"],
    features: ["Checkout Optimization", "Cart Experience", "UX Enhancements", "Store Optimization"],
    image: "/project-images/full website/cleanguards.com.webp",
    pages: [{ key: "bigcommerce" }],
    services: [{ key: "bigcommerce" }],
  },
  {
    slug: "alldogboots",
    name: "ALLDOGBOOTS",
    category: "Pet Accessories",
    domain: "alldogboots.com",
    platform: "Volusion",
    position: 1,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: ["Dynamic Product Pages", "Mobile Optimization", "Smart Product Filters", "Product Experience"],
    image: "/project-images/full website/alldogboots.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "tpms-bargains",
    name: "TPMS BARGAINS",
    category: "Auto Parts",
    domain: "tpmsbargains.com",
    platform: "Volusion",
    position: 2,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: ["Premium Store Redesign", "Conversion Optimization", "Technical SEO", "Schema Implementation"],
    image: "/project-images/full website/tpmsbargains.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "palette-by-nature",
    name: "PALETTE BY NATURE",
    category: "Hair Colour",
    domain: "palettebynature.com",
    platform: "Volusion",
    position: 3,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: [
      "Performance Optimization",
      "Navigation Optimization",
      "Checkout Experience",
      "UX Enhancements",
    ],
    image: "/project-images/full website/palettebynature.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "trade-show-displays-us",
    name: "TRADE SHOW DISPLAYS US",
    category: "Trade Show Displays",
    domain: "tradeshowdisplaysus.com",
    platform: "Volusion",
    position: 4,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: [
      "Premium Store Redesign",
      "Conversion Optimization",
      "Technical SEO",
      "Core Web Vitals Optimization",
    ],
    image: "/project-images/full website/tradeshowdisplaysus.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "exotic-fragrances",
    name: "EXOTIC FRAGRANCES",
    category: "Fragrance & Perfumes",
    domain: "exoticfragrances.com",
    platform: "Volusion",
    position: 5,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: ["Navigation Optimization", "Store Architecture", "Product Discovery", "UX Enhancements"],
    image: "/project-images/full website/exoticfragrances.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "adorable-kids",
    name: "ADORABLE KIDS",
    category: "Kids Clothing",
    domain: "adorable-kids.com",
    platform: "Volusion",
    position: 6,
    tags: ["Volusion", "HTML / CSS", "JavaScript", "jQuery", "App Integration"],
    features: ["Cart Optimization", "Mobile Optimization", "UX Enhancements", "Store Optimization"],
    image: "/project-images/full website/adorable-kids.com.webp",
    pages: [{ key: "volusion" }],
    services: [{ key: "volusion" }],
  },
  {
    slug: "data-sketches",
    name: "DATA SKETCHES",
    category: "Data Visualization",
    domain: "datasketch.es",
    platform: "Webflow",
    position: 1,
    tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Blog Experience", "UI Enhancements", "Bug Resolution", "UX Optimization"],
    image: "/project-images/full website/datasketch.es.webp",
    pages: [{ key: "webflow" }, { key: "website-development", position: 10 }],
    services: [{ key: "webflow" }, { key: "website-development", position: 10 }],
  },
  {
    slug: "mixvibes",
    name: "MIXVIBES",
    category: "Music Software",
    domain: "mixvibes.com",
    platform: "Webflow",
    position: 2,
    tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Premium Store Design", "Brand Experience", "Mobile Optimization", "Technical SEO"],
    image: "/project-images/full website/mixvibes.com.webp",
    pages: [{ key: "webflow" }, { key: "website-development", position: 11 }],
    services: [{ key: "webflow" }, { key: "website-development", position: 11 }],
  },
  {
    slug: "instant-systems",
    name: "INSTANT SYSTEMS",
    category: "Smart Kiosks / Automation",
    domain: "instantsystems.se",
    platform: "Webflow",
    position: 3,
    tags: ["Webflow", "HTML / CSS", "JavaScript", "App Integration"],
    features: [
      "Premium Store Design",
      "Product Experience",
      "Mobile Optimization",
      "Performance Optimization",
    ],
    image: "/project-images/full website/instantsystems.se.webp",
    pages: [{ key: "webflow" }, { key: "website-development", position: 12 }],
    services: [{ key: "webflow" }, { key: "website-development", position: 12 }],
  },
  {
    slug: "quantel",
    name: "QUANTEL",
    category: "Wealth Tech / Fintech",
    domain: "quantel.ai",
    platform: "Webflow",
    position: 4,
    tags: ["Webflow", "HTML / CSS", "JavaScript", "Figma"],
    features: ["Figma Implementation", "Custom Page Development", "Mobile Optimization", "UX Enhancements"],
    image: "/project-images/full website/quantel.ai.webp",
    pages: [{ key: "webflow" }, { key: "website-development", position: 13 }],
    services: [{ key: "webflow" }, { key: "website-development", position: 13 }],
  },
  {
    slug: "dr-mindy-pelz",
    name: "DR. MINDY PELZ",
    category: "Women's Wellness",
    domain: "drmindypelz.com",
    platform: "Wix",
    position: 1,
    tags: ["Wix", "HTML / CSS", "JavaScript", "App Integration"],
    features: ["Website Design", "Brand Experience", "Custom Landing Pages", "Mobile Optimization"],
    image: "/project-images/full website/drmindypelz.com.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 2 }],
  },
  {
    slug: "dumb-ways-to-die",
    name: "DUMB WAYS TO DIE",
    category: "Gaming",
    domain: "dumbwaystodie.com",
    platform: "Wix",
    position: 2,
    tags: ["Wix", "HTML / CSS", "JavaScript", "Figma"],
    features: ["Interactive Experience", "Custom Frontend", "Motion Design", "Performance Optimization"],
    image: "/project-images/full website/dumbwaystodie.com.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 3 }],
  },
  {
    slug: "darshan-metal",
    name: "DARSHAN METAL",
    category: "Metal Supply",
    domain: "darshanmetal.in",
    platform: "WordPress",
    position: 1,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["Website Design", "Product Showcase", "Quote Request System", "User Experience"],
    image: "/project-images/full website/darshanmetal.in.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 4 }],
  },
  {
    slug: "akshar-technocast",
    name: "AKSHAR TECHNOCAST",
    category: "Industrial Manufacturing",
    domain: "akshargroups.in",
    platform: "WordPress",
    position: 2,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: [
      "Corporate Website Design",
      "Performance Optimization",
      "Information Architecture",
      "Trust-Building UX",
    ],
    image: "/project-images/full website/akshargroups.in.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 5 }],
  },
  {
    slug: "globaltv",
    name: "GLOBALTV",
    category: "Digital Media",
    domain: "globaltv.in",
    platform: "WordPress",
    position: 3,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: [
      "News Portal Design",
      "Content Architecture",
      "Navigation Optimization",
      "Performance Optimization",
    ],
    image: "/project-images/full website/globaltv.in.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 6 }],
  },
  {
    slug: "that-computer-chap",
    name: "THAT COMPUTER CHAP",
    category: "IT Services",
    domain: "thatcomputerchap.co.uk",
    platform: "WordPress",
    position: 4,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["Product Experience", "Navigation Optimization", "Store Architecture", "Shopping Experience"],
    image: "/project-images/full website/thatcomputerchap.co.uk.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 7 }],
  },
  {
    slug: "online-ambassadors",
    name: "ONLINE AMBASSADORS",
    category: "Software & Digital Agency",
    domain: "onlineambassadors.net",
    platform: "WordPress",
    position: 5,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["Premium Website Design", "Brand Experience", "Conversion Optimization", "Visual Hierarchy"],
    image: "/project-images/full website/onlineambassadors.net.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 8 }],
  },
  {
    slug: "mega-media-news",
    name: "MEGA MEDIA NEWS",
    category: "News Portal",
    domain: "megamedianews.com",
    platform: "WordPress",
    position: 6,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["News Portal Design", "Content Architecture", "Navigation Optimization", "Reading Experience"],
    image: "/project-images/full website/megamedianews.com.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 9 }],
  },
  {
    slug: "fxhyp",
    name: "FXHYP",
    category: "Forex Education",
    domain: "fxhyp.com",
    platform: "WordPress",
    position: 7,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["Premium Website Design", "Trust-Centered UX", "Information Architecture", "Brand Experience"],
    image: "/project-images/full website/fxhyp.com.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 14 }],
  },
  {
    slug: "gaav-naturals",
    name: "GAAV NATURALS",
    category: "Natural Honey",
    domain: "gaavnaturals.in",
    platform: "WooCommerce",
    position: 8,
    tags: ["WordPress", "WooCommerce", "JS", "HTML / CSS", "App Integration"],
    features: ["Store Setup", "Navigation Optimization", "Checkout Experience", "Product Discovery"],
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 15 }],
  },
  {
    slug: "onsite-tech-solutions",
    name: "ONSITE TECH SOLUTIONS",
    category: "Managed IT Services",
    domain: "onsitetechsolutions.com.au",
    platform: "WordPress",
    position: 9,
    tags: ["WordPress", "JS", "HTML / CSS", "App Integration"],
    features: ["Modern Storefront", "Responsive Design", "User Experience", "Interface Optimization"],
    image: "/project-images/full website/onsitetechsolutions.com.au.webp",
    pages: [{ key: "website-development" }],
    services: [{ key: "website-development", position: 16 }],
  },
];
