/*
 * Post-build SEO files, derived from what is actually linked on the site.
 *
 * Crawls the exported site (out/) from the homepage, following real
 * <a href> links, then writes:
 *   - out/sitemap.xml  every linked page (except noindex ones)
 *   - out/robots.txt   blocks crawling of every page nothing links to
 *
 * So commenting a link out (navigation or page) removes its target from the
 * sitemap and closes it to crawlers at the next build; restoring the link
 * reverses both. Unlinked pages stay reachable by URL for visitors.
 *
 * URLs redirected in vercel.json are left out of both files: crawlers must
 * be allowed to fetch them, or they'd never see the 301.
 */
import { readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

const OUT = "out";
const SITE = "https://triyanshitechnologies.com";

/** Higher priority for the key pages; everything else gets the default. */
const PRIORITY = {
  "/": 1,
  "/services/ecommerce": 0.9,
  "/services/enterprise-solutions": 0.9,
  "/company/about-us": 0.8,
  "/portfolio": 0.8,
  "/tools": 0.8,
  "/contact-us/contact-us": 0.6,
};
const DEFAULT_PRIORITY = 0.7;

/** Every exported page route (404 pages excluded). */
function allRoutes(dir = OUT) {
  const routes = [];
  for (const name of readdirSync(dir)) {
    const full = path.join(dir, name);
    if (statSync(full).isDirectory()) {
      if (name !== "_next" && name !== "_not-found") routes.push(...allRoutes(full));
    } else if (name.endsWith(".html") && name !== "404.html" && name !== "_not-found.html") {
      const rel = path
        .relative(OUT, full)
        .replace(/\\/g, "/")
        .replace(/\.html$/, "");
      routes.push(rel === "index" ? "/" : `/${rel}`);
    }
  }
  return routes;
}

const redirected = new Set(JSON.parse(readFileSync("vercel.json", "utf8")).redirects.map((r) => r.source));
const routes = new Set(allRoutes().filter((route) => !redirected.has(route)));
const fileFor = (route) => path.join(OUT, route === "/" ? "index.html" : `${route.slice(1)}.html`);

/** Internal page links in a page's HTML, as normalized routes. */
function linksIn(html) {
  const links = [];
  for (const [, raw] of html.matchAll(/<a\b[^>]*?\shref="([^"]+)"/g)) {
    let url;
    try {
      url = new URL(raw.replace(/&amp;/g, "&"), SITE);
    } catch {
      continue;
    }
    if (url.origin !== SITE) continue;
    links.push(
      decodeURIComponent(url.pathname)
        .replace(/\.html$/, "")
        .replace(/\/+$/, "") || "/",
    );
  }
  return links;
}

const noindex = (html) => /<meta name="robots" content="[^"]*noindex/.test(html);

// Breadth-first crawl from the homepage.
const linked = new Set(["/"]);
const queue = ["/"];
const indexable = [];
while (queue.length) {
  const route = queue.shift();
  const html = readFileSync(fileFor(route), "utf8");
  if (!noindex(html)) indexable.push(route);
  for (const link of linksIn(html)) {
    if (routes.has(link) && !linked.has(link)) {
      linked.add(link);
      queue.push(link);
    }
  }
}
const unlinked = [...routes].filter((route) => !linked.has(route)).sort();

// sitemap.xml
const byPath = (a, b) => (a === "/" ? -1 : b === "/" ? 1 : a.localeCompare(b));
const lastmod = new Date().toISOString();
const urls = indexable
  .sort(byPath)
  .map(
    (route) =>
      `<url>\n<loc>${SITE}${route === "/" ? "" : route}</loc>\n<lastmod>${lastmod}</lastmod>\n<priority>${PRIORITY[route] ?? DEFAULT_PRIORITY}</priority>\n</url>`,
  );
writeFileSync(
  path.join(OUT, "sitemap.xml"),
  `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls.join("\n")}\n</urlset>\n`,
);

// robots.txt — "$" makes each rule an exact match, so blocking /services
// doesn't also block /services/ecommerce.
const robots = [
  "User-agent: *",
  "Allow: /",
  ...(unlinked.length
    ? ["", "# Not linked from anywhere on the site (generated by scripts/crawl-seo.mjs)"]
    : []),
  ...unlinked.map((route) => `Disallow: ${route}$`),
  "",
  `Sitemap: ${SITE}/sitemap.xml`,
  "",
].join("\n");
writeFileSync(path.join(OUT, "robots.txt"), robots);

console.log(
  `[seo] sitemap: ${indexable.length} linked pages | robots.txt: ${unlinked.length} unlinked pages blocked`,
);
